[package]
name = "azure-docs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "azure_docs"
path = "src/main.rs"

[dependencies]
azure-foundation = { path = "../azure-foundation" }
azure-core = { path = "../azure-core" }
azure-rooter = { path = "../azure-rooter" }

[dev-dependencies]
azure-engine = { path = "../azure-engine" }
azure-stockage = { path = "../azure-stockage" }
