<container.ecran>
    <container.chrome><container.pastille><!container><container.pastille><!container><container.pastille><!container><text.url>pixel-shop.test/boutique<!text><!container>
    <container.app>
        <container.tete>
            <text.logo>PIXEL SHOP<!text>
            <text.nav.actif>BOUTIQUE<!text><text.nav>NOUVEAUTÉS<!text><text.nav>MON COMPTE<!text>
            <text.panier>PANIER (3)<!text>
        <!container>
        <container.corps>
            <container.filtres>
                <text.f-titre>CATÉGORIES<!text>
                <text.f.actif>Tout voir<!text>
                <text.f>Armes<!text>
                <text.f>Potions<!text>
                <text.f>Armures<!text>
                <text.f>Objets<!text>
                <text.f-titre>PRIX<!text>
                <text.f>Moins de 5 €<!text>
                <text.f>5 à 15 €<!text>
            <!container>
            <container.grille>
                <container.produit><text.badge>nouveau<!text>
                    <container.vitrine><container.sprite><container.px-ligne><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px.c-r><!container><container.px.c-r><!container><container.px><!container><container.px><!container><container.px.c-r><!container><container.px.c-r><!container><container.px><!container><!container><container.px-ligne><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><!container><container.px-ligne><container.px.c-r><!container><container.px.c-w><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><!container><container.px-ligne><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><!container><container.px-ligne><container.px><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px><!container><container.px.c-r><!container><container.px.c-r><!container><container.px><!container><container.px><!container><container.px><!container><!container><!container><!container>
                    <text.p-nom>Cœur de vie<!text>
                    <container.p-bas><text.p-prix>4,90 €<!text><text.p-ajout>+ PANIER<!text><!container>
                <!container>
                <container.produit>
                    <container.vitrine><container.sprite><container.px-ligne><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px.c-s><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px.c-s><!container><container.px.c-S><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px.c-s><!container><container.px.c-S><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px.c-s><!container><container.px.c-S><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px.c-Y><!container><container.px><!container><container.px><!container><container.px.c-s><!container><container.px.c-S><!container><container.px><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px.c-Y><!container><container.px.c-s><!container><container.px.c-S><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px.c-Y><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px.c-Y><!container><container.px><!container><container.px.c-Y><!container><container.px><!container><container.px><!container><container.px><!container><container.px><!container><!container><!container><!container>
                    <text.p-nom>Épée en fer<!text>
                    <container.p-bas><text.p-prix>12,00 €<!text><text.p-ajout>+ PANIER<!text><!container>
                <!container>
                <container.produit>
                    <container.vitrine><container.sprite><container.px-ligne><container.px><!container><container.px><!container><container.px><!container><container.px.c-k><!container><container.px.c-k><!container><container.px><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px><!container><container.px.c-s><!container><container.px.c-s><!container><container.px><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px.c-p><!container><container.px.c-p><!container><container.px.c-p><!container><container.px.c-p><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px.c-p><!container><container.px.c-p><!container><container.px.c-p><!container><container.px.c-p><!container><container.px.c-p><!container><container.px.c-p><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px.c-p><!container><container.px.c-w><!container><container.px.c-p><!container><container.px.c-p><!container><container.px.c-p><!container><container.px.c-p><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px.c-p><!container><container.px.c-p><!container><container.px.c-p><!container><container.px.c-p><!container><container.px.c-p><!container><container.px.c-p><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px.c-P><!container><container.px.c-P><!container><container.px.c-P><!container><container.px.c-P><!container><container.px.c-P><!container><container.px.c-P><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px.c-P><!container><container.px.c-P><!container><container.px.c-P><!container><container.px.c-P><!container><container.px><!container><container.px><!container><!container><!container><!container>
                    <text.p-nom>Potion de mana<!text>
                    <container.p-bas><text.p-prix>3,50 €<!text><text.p-ajout>+ PANIER<!text><!container>
                <!container>
                <container.produit><text.badge>-20 %<!text>
                    <container.vitrine><container.sprite><container.px-ligne><container.px><!container><container.px><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-y><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px.c-y><!container><container.px.c-Y><!container><container.px.c-Y><!container><container.px.c-Y><!container><container.px.c-Y><!container><container.px.c-y><!container><container.px><!container><!container><container.px-ligne><container.px.c-y><!container><container.px.c-Y><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-Y><!container><container.px.c-y><!container><!container><container.px-ligne><container.px.c-y><!container><container.px.c-Y><!container><container.px.c-y><!container><container.px.c-Y><!container><container.px.c-Y><!container><container.px.c-y><!container><container.px.c-Y><!container><container.px.c-y><!container><!container><container.px-ligne><container.px.c-y><!container><container.px.c-Y><!container><container.px.c-y><!container><container.px.c-Y><!container><container.px.c-Y><!container><container.px.c-y><!container><container.px.c-Y><!container><container.px.c-y><!container><!container><container.px-ligne><container.px.c-y><!container><container.px.c-Y><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-Y><!container><container.px.c-y><!container><!container><container.px-ligne><container.px><!container><container.px.c-y><!container><container.px.c-Y><!container><container.px.c-Y><!container><container.px.c-Y><!container><container.px.c-Y><!container><container.px.c-y><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-y><!container><container.px><!container><container.px><!container><!container><!container><!container>
                    <text.p-nom>Sac de pièces<!text>
                    <container.p-bas><text.p-prix>8,00 €<!text><text.p-ajout>+ PANIER<!text><!container>
                <!container>
                <container.produit>
                    <container.vitrine><container.sprite><container.px-ligne><container.px><!container><container.px.c-B><!container><container.px.c-B><!container><container.px.c-B><!container><container.px.c-B><!container><container.px.c-B><!container><container.px.c-B><!container><container.px><!container><!container><container.px-ligne><container.px.c-B><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-B><!container><!container><container.px-ligne><container.px.c-B><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-B><!container><!container><container.px-ligne><container.px.c-B><!container><container.px.c-b><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-b><!container><container.px.c-B><!container><!container><container.px-ligne><container.px.c-B><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-y><!container><container.px.c-y><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-B><!container><!container><container.px-ligne><container.px><!container><container.px.c-B><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-B><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px.c-B><!container><container.px.c-b><!container><container.px.c-b><!container><container.px.c-B><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px><!container><container.px.c-B><!container><container.px.c-B><!container><container.px><!container><container.px><!container><container.px><!container><!container><!container><!container>
                    <text.p-nom>Bouclier bleu<!text>
                    <container.p-bas><text.p-prix>15,00 €<!text><text.p-ajout>+ PANIER<!text><!container>
                <!container>
                <container.produit>
                    <container.vitrine><container.sprite><container.px-ligne><container.px><!container><container.px><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px.c-r><!container><container.px.c-w><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-w><!container><container.px.c-r><!container><container.px><!container><!container><container.px-ligne><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><!container><container.px-ligne><container.px.c-r><!container><container.px.c-w><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-r><!container><container.px.c-w><!container><container.px.c-r><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px.c-o><!container><container.px.c-o><!container><container.px.c-o><!container><container.px.c-o><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px.c-o><!container><container.px.c-k><!container><container.px.c-k><!container><container.px.c-o><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px.c-o><!container><container.px.c-o><!container><container.px.c-o><!container><container.px.c-o><!container><container.px><!container><container.px><!container><!container><container.px-ligne><container.px><!container><container.px><!container><container.px.c-o><!container><container.px.c-o><!container><container.px.c-o><!container><container.px.c-o><!container><container.px><!container><container.px><!container><!container><!container><!container>
                    <text.p-nom>Champignon<!text>
                    <container.p-bas><text.p-prix>2,90 €<!text><text.p-ajout>+ PANIER<!text><!container>
                <!container>
            <!container>
        <!container>
    <!container>
<!container>
