[package]
name = "azure-note"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "azure_note"
path = "src/main.rs"

[dependencies]
azure-foundation = { path = "../azure-foundation" }
azure-core = { path = "../azure-core" }
azure-rooter = { path = "../azure-rooter" }

[dev-dependencies]
azure-docs = { path = "../azure-docs" }
azure-engine = { path = "../azure-engine" }
azure-manager = { path = "../azure-manager" }
azure-service = { path = "../azure-service" }
azure-stockage = { path = "../azure-stockage" }
